name: Security Testing

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  sast:
    uses: p2p-org/security-workflows/.github/workflows/sast.yaml@main
    secrets: inherit
  docker-scan:
    uses: p2p-org/security-workflows/.github/workflows/docker-scan.yaml@main
    with:
      image_name: ${{ github.repository }}
      docker_file_path: 'Dockerfile'
      workdir: '.'
    secrets: inherit
