# This is a basic workflow to help you get started with Actions

name: Security checks

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 13 * * 1"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install safety
        run: pip install safety
      
      - name: Validate requriments.txt
        run: safety check -r requirements.txt

